"""initial control schema

Revision ID: 1e455bfadcce
Revises: 
Create Date: 2026-09-19 10:21:52.879341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import mf_app.db.types

# revision identifiers, used by Alembic.
revision: str = '1e455bfadcce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_institutions',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONING', 'ACTIVE', 'FAILED', 'SUSPENDED', name='mfinstitutionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('cp_project_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('cp_database_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('db_host', sa.String(length=255), nullable=True),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(length=100), nullable=True),
    sa.Column('db_username', sa.String(length=100), nullable=True),
    sa.Column('encrypted_db_password', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mf_institutions_slug'), 'mf_institutions', ['slug'], unique=True)
    op.create_table('mf_jobs',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', name='mfjobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('institution_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_platform_accounts',
    sa.Column('cp_organization_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('cp_email', sa.String(length=255), nullable=False),
    sa.Column('encrypted_cp_password', sa.String(length=500), nullable=False),
    sa.Column('cached_access_token', sa.String(length=2000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_staff_users',
    sa.Column('institution_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.Enum('INSTITUTION_ADMIN', 'BRANCH_MANAGER', 'LOAN_OFFICER', 'TELLER', name='mfstaffrole', native_enum=False, length=30), nullable=False),
    sa.Column('tenant_agent_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['mf_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'email', name='uq_mf_staff_institution_email')
    )
    op.create_index(op.f('ix_mf_staff_users_institution_id'), 'mf_staff_users', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mf_staff_users_institution_id'), table_name='mf_staff_users')
    op.drop_table('mf_staff_users')
    op.drop_table('mf_platform_accounts')
    op.drop_table('mf_jobs')
    op.drop_index(op.f('ix_mf_institutions_slug'), table_name='mf_institutions')
    op.drop_table('mf_institutions')
    # ### end Alembic commands ###
