"""phase 9.3 loans

Revision ID: 0f356ef160e1
Revises: ce24430a9cab
Create Date: 2026-09-19 12:31:17.299421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import mf_app.db.types

# revision identifiers, used by Alembic.
revision: str = '0f356ef160e1'
down_revision: Union[str, None] = 'ce24430a9cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('amortization_method', sa.Enum('DECLINING_BALANCE', 'FLAT', name='amortizationmethod', native_enum=False, length=20), nullable=False),
    sa.Column('periodic_interest_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('min_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_term_months', sa.Integer(), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('loans',
    sa.Column('customer_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('product_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVE', 'CLOSED', 'DEFAULTED', name='loanstatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by_staff_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('outstanding_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repayment_schedules',
    sa.Column('loan_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repayment_schedule_lines',
    sa.Column('schedule_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalty_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='repaymentlinestatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['repayment_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment_schedule_lines')
    op.drop_table('repayment_schedules')
    op.drop_table('loans')
    op.drop_table('loan_products')
    # ### end Alembic commands ###
