"""initial tenant schema

Revision ID: c9149e0d2f40
Revises: 
Create Date: 2026-09-19 10:22:00.517569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import mf_app.db.types

# revision identifiers, used by Alembic.
revision: str = 'c9149e0d2f40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('institution_profile',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('branch_id', mf_app.db.types.GUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('INSTITUTION_ADMIN', 'BRANCH_MANAGER', 'LOAN_OFFICER', 'TELLER', name='mfstaffrole', native_enum=False, length=30), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    op.drop_table('institution_profile')
    op.drop_table('branches')
    # ### end Alembic commands ###
