"""phase 9.2 ledger and savings

Revision ID: ce24430a9cab
Revises: c9149e0d2f40
Create Date: 2026-09-19 12:18:10.961141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import mf_app.db.types

# revision identifiers, used by Alembic.
revision: str = 'ce24430a9cab'
down_revision: Union[str, None] = 'c9149e0d2f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_accounts',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('normal_balance_side', sa.String(length=10), nullable=False),
    sa.Column('balance_cached', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('savings_products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('transactions',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('customers',
    sa.Column('branch_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus', native_enum=False, length=20), nullable=False),
    sa.Column('identity_documents', sa.JSON(), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('transaction_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('account_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledgerdirection', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_table('savings_accounts',
    sa.Column('customer_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('product_id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='savingsaccountstatus', native_enum=False, length=20), nullable=False),
    sa.Column('balance_cached', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', mf_app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['savings_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_accounts')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('customers')
    op.drop_table('transactions')
    op.drop_table('savings_products')
    op.drop_table('internal_accounts')
    # ### end Alembic commands ###
