"""phase4 roles extensions sql editor

Revision ID: 02bf785abd33
Revises: b3489595e8e2
Create Date: 2026-09-18 21:23:37.732243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '02bf785abd33'
down_revision: Union[str, None] = 'b3489595e8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_executions',
    sa.Column('database_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('query_text', sa.String(length=10000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_queries',
    sa.Column('database_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('query_text', sa.String(length=10000), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table: SQLite (local dev) can't ALTER a constraint in place and
    # needs the copy-and-move strategy; Postgres (prod) just runs plain ALTER
    # statements under the hood either way.
    with op.batch_alter_table('database_credentials') as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_unique_constraint('uq_database_credentials_role_name', ['role_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database_credentials') as batch_op:
        batch_op.drop_constraint('uq_database_credentials_role_name', type_='unique')
        batch_op.drop_column('is_primary')
        batch_op.drop_column('display_name')
    op.drop_table('saved_queries')
    op.drop_table('query_executions')
    # ### end Alembic commands ###
