"""phase8 webhooks

Revision ID: 2d631f31d1dd
Revises: dcb65b0f22af
Create Date: 2026-09-19 08:11:15.765986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '2d631f31d1dd'
down_revision: Union[str, None] = 'dcb65b0f22af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('organization_id', app.db.types.GUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=500), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('webhook_id', app.db.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='webhookdeliverystatus', native_enum=False, length=20), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_deliveries')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
