"""phase13 api key auth

Revision ID: 3675a60c00be
Revises: faba0e0ea8ab
Create Date: 2026-09-22 19:33:13.913531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '3675a60c00be'
down_revision: Union[str, None] = 'faba0e0ea8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('user_id', app.db.types.GUID(), nullable=True))
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'user_id')
    # ### end Alembic commands ###
