"""phase10 billing

Revision ID: 3889e63a4a84
Revises: 2d631f31d1dd
Create Date: 2026-09-19 13:23:31.990379

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '3889e63a4a84'
down_revision: Union[str, None] = '2d631f31d1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quotas', sa.JSON(), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Seed the plans every organization/quota check needs to exist out of the
    # box — app/api/v1/endpoints/organizations.py refuses to create an org
    # without a "free" plan already present (cf. docs/architecture/08 §8.12:
    # quotas/pricing are data, never hardcoded, but a sensible default must
    # still exist at deploy time rather than requiring a manual seeding step).
    plans_table = sa.table(
        'plans',
        sa.column('id', app.db.types.GUID()),
        sa.column('name', sa.String()),
        sa.column('quotas', sa.JSON()),
        sa.column('pricing', sa.JSON()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(plans_table, [
        {
            'id': uuid.uuid4(),
            # max_storage_gb=20, not something smaller like 5: DatabaseCreate's
            # own default storage_limit_gb is 10 GB (cf. app/schemas/database.py),
            # set long before quotas existed — a free plan whose quota is below
            # that default would reject the very first database anyone creates
            # with default settings. Caught by this migration's own test seed
            # (backend/tests/conftest.py must mirror these numbers exactly).
            'name': 'free',
            'quotas': {'max_databases': 1, 'max_storage_gb': 20, 'max_cpu_total': 1},
            'pricing': {'base_fee': '0'},
            'is_active': True,
        },
        {
            'id': uuid.uuid4(),
            'name': 'pro',
            'quotas': {'max_databases': 10, 'max_storage_gb': 200, 'max_cpu_total': 16},
            'pricing': {
                'base_fee': '25.00',
                'cpu_hours': '0.02',
                'storage_gb_hours': '0.0005',
            },
            'is_active': True,
        },
    ])
    op.create_table('subscriptions',
    sa.Column('organization_id', app.db.types.GUID(), nullable=False),
    sa.Column('plan_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', name='subscriptionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('invoices',
    sa.Column('organization_id', app.db.types.GUID(), nullable=False),
    sa.Column('subscription_id', app.db.types.GUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'PAID', 'VOID', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', app.db.types.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('database_id', app.db.types.GUID(), nullable=False),
    sa.Column('metric', sa.Enum('CPU_HOURS', 'STORAGE_GB_HOURS', 'CONNECTIONS', 'EGRESS_GB', name='usagemetric', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_database_id'), 'usage_records', ['database_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_database_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('subscriptions')
    op.drop_table('plans')
    # ### end Alembic commands ###
