"""phase14 token version

Revision ID: 9e7d7fcad4e3
Revises: 3675a60c00be
Create Date: 2026-09-22 20:09:57.847946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7d7fcad4e3'
down_revision: Union[str, None] = '3675a60c00be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so this doesn't fail on the existing (non-empty) users
    # table — every already-registered user starts at version 0, same as the
    # ORM model's Python-side default for brand new rows.
    op.add_column(
        'users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
