"""phase3 orchestrator clusters databases jobs

Revision ID: b3489595e8e2
Revises: 76b489b900f0
Create Date: 2026-09-18 20:26:36.074622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = 'b3489595e8e2'
down_revision: Union[str, None] = '76b489b900f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('organization_id', app.db.types.GUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', app.db.types.GUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_table('clusters',
    sa.Column('region_id', app.db.types.GUID(), nullable=False),
    sa.Column('topology', sa.Enum('SINGLE', 'PRIMARY_REPLICA', name='clustertopology', native_enum=False, length=20), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('postgres_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONING', 'ACTIVE', 'DEGRADED', 'DELETED', name='clusterstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_members',
    sa.Column('cluster_id', app.db.types.GUID(), nullable=False),
    sa.Column('node_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'REPLICA', name='clustermemberrole', native_enum=False, length=20), nullable=False),
    sa.Column('replication_lag_bytes', sa.Integer(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('databases',
    sa.Column('project_id', app.db.types.GUID(), nullable=False),
    sa.Column('region_id', app.db.types.GUID(), nullable=False),
    sa.Column('cluster_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('physical_name', sa.String(length=63), nullable=False),
    sa.Column('isolation_level', sa.Enum('SHARED', 'DEDICATED', name='isolationlevel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'RUNNING', 'UPDATING', 'SUSPENDING', 'SUSPENDED', 'RESTORING', 'MIGRATING', 'FAILING', 'FAILED', 'DELETING', 'DELETED', name='databasestatus', native_enum=False, length=20), nullable=False),
    sa.Column('cpu_limit', sa.Integer(), nullable=False),
    sa.Column('ram_limit_mb', sa.Integer(), nullable=False),
    sa.Column('storage_limit_gb', sa.Integer(), nullable=False),
    sa.Column('connection_host', sa.String(length=255), nullable=True),
    sa.Column('connection_port', sa.Integer(), nullable=True),
    sa.Column('backup_policy', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_name'),
    sa.UniqueConstraint('project_id', 'name', name='uq_database_project_name')
    )
    op.create_table('database_credentials',
    sa.Column('database_id', app.db.types.GUID(), nullable=False),
    sa.Column('role_name', sa.String(length=63), nullable=False),
    sa.Column('encrypted_password', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.Enum('APP', 'READONLY', 'ADMIN', name='credentialscope', native_enum=False, length=20), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('database_events',
    sa.Column('database_id', app.db.types.GUID(), nullable=False),
    sa.Column('job_id', app.db.types.GUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nodes', sa.Column('postgres_port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'postgres_port')
    op.drop_table('database_events')
    op.drop_table('database_credentials')
    op.drop_table('databases')
    op.drop_table('cluster_members')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
