"""phase6 high availability

Revision ID: dcb65b0f22af
Revises: d3588dbb41a9
Create Date: 2026-09-18 22:53:03.572930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = 'dcb65b0f22af'
down_revision: Union[str, None] = 'd3588dbb41a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_events',
    sa.Column('cluster_id', app.db.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_events')
    # ### end Alembic commands ###
