"""phase12 oauth accounts

Revision ID: faba0e0ea8ab
Revises: 28c5766275ca
Create Date: 2026-09-20 14:38:26.278919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types

# revision identifiers, used by Alembic.
revision: str = 'faba0e0ea8ab'
down_revision: Union[str, None] = '28c5766275ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'GITHUB', name='oauthprovidername', native_enum=False, length=20), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauth_provider_account')
    )
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
